# Generated by Django 5.1.1 on 2024-09-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_acessorio_alter_veiculo_anofabricacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='anoFabricacao',
            field=models.IntegerField(),
        ),
    ]
