# Generated by Django 5.1.1 on 2024-09-17 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0004_veiculo_acessorios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='acessorios',
        ),
        migrations.AddField(
            model_name='acessorio',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='veiculos.veiculo'),
        ),
    ]
